---
- name: PTA Packages
  hosts: all
  gather_facts: no
  become: yes
  tasks:

  - name: Install package foo
    ansible.builtin.package:
      name:
        - git
        #- docker-compose
        #- docker.io
      state: present