---
- name: Conjur Hosts
  hosts: all
  gather_facts: no
  become: yes
  tasks:

  - name: Import a key from a url
    ansible.builtin.rpm_key:
      state: present
      key: https://download.docker.com/linux/ubuntu/gpg

  - name: Upgrade all packages
    ansible.builtin.yum:
      name: '*'
      state: latest

  # - name: Add repository
  # ansible.builtin.yum_repository:
  #   name: epel
  #   description: EPEL YUM repo
  #   baseurl: https://download.docker.com/linux/rhel/

  # - name: Package Install
  #    ansible.builtin.package:
  #      name:
  #        - git
  #        - yum-utils
  #        - docker-compose
  #        #- docker.io
  #        #- docker-ce
  #        #- docker-ce-cli
  #        #- containerd.io
  #      state: latest