---
- name: linux_patching
  hosts: all
  become: true
  gather_facts: no
  tasks:

    - name: Update all packages to their latest version
      ansible.builtin.apt:
        name: "*"
        state: latest
