---
- name: Windows Updates
  hosts: all
  become: false
  gather_facts: no
  tasks:

  # - name: Install all security, critical, and rollup updates without a scheduled task
  #   win_updates:
  #      category_names:
  #        - SecurityUpdates
  #        - CriticalUpdates
  #        - UpdateRollups

  - name: Search and download Windows updates without installing them
    win_updates:
      state: downloaded